[package]
name = "{{crate_name}}-lib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Logging crates
tracing = { workspace = true }

# Error handling crates
thiserror = { workspace = true }
